name: jing_hong_v4
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  async: ^2.12.0
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_svg: ^2.1.0
  freezed_annotation: ^3.0.0
  go_router: ^15.1.1
  flutter_math_fork: ^0.7.3
  gpt_markdown: ^1.0.19
  
  intl: ^0.20.2
  json_annotation: ^4.9.0
  path: ^1.9.1
  provider: ^6.1.5
  sqflite: ^2.4.2
  sqflite_common_ffi_web: ^1.0.0 # https://github.com/tekartik/sqflite/tree/master/packages_web/sqflite_common_ffi_web#setup-binaries
  shared_preferences: ^2.5.3

  image_picker: ^1.1.2
  image_picker_for_web: ^3.0.6
  uuid: ^4.5.1
  permission_handler: ^12.0.1
  path_provider: ^2.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true
  assets:
#    - assets/google_fonts/
    - assets/images/home.png
    - assets/images/chat.png
    - assets/images/about.png
    - assets/images/avatar.png
    - assets/images/avatar-small.png
    - assets/images/born.jpg
    - assets/images/highschool.jpg
    - assets/images/university.jpg
    - assets/images/guangzhou.jpg
    - assets/images/chengdu.jpg
    - assets/images/now.jpg
    - assets/images/study.jpg
    - assets/images/millstone.png
    - assets/images/jinghong_logo.png
    - assets/images/kimi.svg
    - assets/images/deepseek.svg
    - assets/images/robot.svg
    - assets/images/Naruto.svg
    - assets/images/qr/qr-code-bytedance.jpg
    - assets/images/qr/qr-code-email.png
    - assets/images/qr/qr-code-github.png
    - assets/images/qr/qr-code-wechat.jpg
    - assets/images/qr/文件不存在提示.png
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          style: normal
#    - family: SourceHanSansSc
#      fonts:
#        - asset: assets/fonts/SourceHanSansSc-Regular.otf
#        - asset: assets/fonts/SourceHanSansSc-Light.otf
#        - asset: assets/fonts/SourceHanSansSc-Heavy.otf
#        - asset: assets/fonts/SourceHanSansSc-Bold.otf
#          style: normal
